### ISSUE TITLE
Exception information

### ISSUE THREAD

**Issue by FraGoTe** [codeinchaos/restful-zend-framework#27]
Message: script 'index/get.phtml' not found in path

**Comment by FraGoTe** [comment]
should I create that view?

**Comment by ahmadnassri** [comment]
if you're accessing it through the browser and have html enabled, then it will attempt to resolve and render using the default zend framework rendering settings.

**Comment by FraGoTe** [comment]
I just realized that my active bootstraping is not working.

**Comment by ahmadnassri** [comment]
should I close this ticket then?

**Comment by FraGoTe** [comment]
Yes thanks!
